# Generated by Django 3.2.11 on 2022-02-08 08:49

import RestorantAPI.models
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cat_img', models.URLField()),
                ('cat_Code', models.CharField(blank=True, default=RestorantAPI.models.deneme, editable=False, max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restorant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.CharField(max_length=100)),
                ('rest_createDate', models.DateField()),
                ('rest_Phone', models.CharField(max_length=12)),
                ('rest_Code', models.CharField(blank=True, default=RestorantAPI.models.deneme, editable=False, max_length=12, unique=True)),
                ('rest_img', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product_Img', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pro_contents', models.TextField()),
                ('category', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='restorant', chained_model_field='restorant', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='RestorantAPI.category')),
                ('restorant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestorantAPI.restorant', to_field='rest_Code')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='restorant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='RestorantAPI.restorant', to_field='rest_Code'),
        ),
    ]
