# Generated by Django 3.2.11 on 2022-02-10 11:44

import RestorantAPI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestorantAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(upload_to=RestorantAPI.models.cat_file_name),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_Img',
            field=models.ImageField(upload_to=RestorantAPI.models.pro_file_name),
        ),
        migrations.AlterField(
            model_name='restorant',
            name='rest_img',
            field=models.ImageField(upload_to=RestorantAPI.models.rest_file_name),
        ),
    ]
