# Generated by Django 2.1.15 on 2021-11-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmplyoeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmplyoeeName', models.CharField(max_length=500)),
                ('Departmen', models.CharField(max_length=500)),
                ('DateOfJoing', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
    ]
