# Generated by Django 4.0.1 on 2022-01-24 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='restorant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='EmployeeApp.restorant', to_field='rest_Code'),
        ),
        migrations.DeleteModel(
            name='Deneme',
        ),
    ]
